name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Deno
      uses: denolib/setup-deno@v1.3.0
      with:
        deno-version: v1.1.0
    - name: Lint
      run: deno run --allow-run run.ts fmt --lint
    - name: Test
      run: deno run --allow-run run.ts test
